name: CI/CD to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # Authenticate Docker with Google Artifact Registry
    - name: Authenticate Docker
      run: gcloud auth configure-docker gcr.io

    # Build and push the Docker image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=gcr.io/cloudintro-448420/dockerintro:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy github-actions@cloudintro-448420.iam.gserviceaccount.com \
          --image gcr.io/cloudintro-448420/dockerintro:latest \
          --region europe-west3 \
          --platform managed \
          --allow-unauthenticated
